cfDeCryptBundle_homepage:
    pattern:  /
    defaults: { _controller: cfDeCryptBundle:Page:index }
    requirements:
        _method:  GET

cfDeCryptBundle_about:
    pattern:  /about
    defaults: { _controller: cfDeCryptBundle:Page:about }
    requirements:
        _method:  GET

cfDeCryptBundle_contact:
    pattern:  /contact
    defaults: { _controller: cfDeCryptBundle:Page:contact }
    requirements:
        _method:  GET|POST

cfDeCryptBundle_rot13:
    pattern:  /rot13
    defaults: { _controller: cfDeCryptBundle:Rot13:show }
    requirements:
        _method:  GET|POST

cfDeCryptBundle_roman2arab:
    pattern:  /roman2arab
    defaults: { _controller: cfDeCryptBundle:Roman2Arab:show }
    requirements:
        _method:  GET|POST
