cfDeCryptBundle_homepage:
    pattern:  /
    defaults: { _controller: cfDeCryptBundle:Page:index }
    requirements:
        _method:  GET

cfDeCryptBundle_about:
    pattern:  /about
    defaults: { _controller: cfDeCryptBundle:Page:about }
    requirements:
        _method:  GET

cfDeCryptBundle_contact:
    pattern:  /contact
    defaults: { _controller: cfDeCryptBundle:Page:contact }
    requirements:
        _method:  GET|POST